version: "3.9"

services:
  backend:
    build: ./backend
    container_name: translation_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: translation_frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend